services:
  backend:
    container_name: blackjack-backend
    build: ./backend
    # Elimina la sección "volumes:" completa
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
      - ML_SERVICE_URL=http://ml-service:5000
      - NODE_ENV=production
    depends_on:
      - db
      - ml-service
    command: npm start

  frontend:
    container_name: blackjack-frontend
    build: ./frontend
    # Elimina la sección "volumes:" completa
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    command: sh -c "npm run build && npx serve -s dist -l 5173"

  nginx:
    container_name: blackjack-nginx
    image: nginx:alpine
    ports:
      - "2280:80"
      - "8443:443"
    volumes:
      - ./requirements/nginx/conf.d/blackjack.conf:/etc/nginx/conf.d/blackjack.conf
      - ./secrets/certs/blackjack.local.crt:/etc/ssl/certs/blackjack.local.crt
      - ./secrets/certs/blackjack.local.key:/etc/ssl/private/blackjack.local.key
    depends_on:
      - frontend
      - backend
      - ml-service

  ml-service:
    container_name: blackjack-ml-service
    build: ./ml_service
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"

  db:
    image: postgres:15-alpine
    container_name: blackjack-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${DATA_PATH}/postgres:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql


  prometheus:
    image: prom/prometheus
    container_name: blackjack-prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "127.0.0.1:9090:9090"
    depends_on:
      - backend

  grafana:
    image: grafana/grafana
    container_name: blackjack-grafana
    ports:
      - "127.0.0.1:3001:3000"
    environment:
    - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
    - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: blackjack-cadvisor
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    restart: unless-stopped

volumes:
  grafana-data:
