global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "backend"
    static_configs:
      - targets: ["blackjack-backend:3000"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["blackjack-cadvisor:8080"]
  
  - job_name: "node"
    static_configs:
      - targets: ["blackjack-node-exporter:9100"]