apiVersion: 1

groups:
  - name: docker-alerts
    folder: docker-alerts
    interval: 30s

    rules:
      - uid: cpu_high
        title: High CPU usage
        condition: C
        for: 1m

        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              expr: sum(rate(container_cpu_usage_seconds_total{instance="cadvisor:8080",name=~"blackjack-.*",name!=""}[5m])) by (name) * 100
              refId: A

          - refId: B
            datasourceUid: __expr__
            model:
              type: reduce
              expression: A
              reducer: last
              settings:
                mode: dropNN
              refId: B

          - refId: C
            datasourceUid: __expr__
            model:
              type: threshold
              expression: B
              conditions:
                - evaluator:
                    type: gt
                    params: [1]
                  operator:
                    type: and
                  reducer:
                    type: last
                  type: query
              refId: C

        annotations:
          summary: "High CPU on {{ $labels.name }}"
        labels:
          severity: warning

      - uid: memory_high
        title: High Memory usage
        condition: D
        for: 1m

        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              expr: sum(container_memory_usage_bytes{instance="cadvisor:8080",name=~"blackjack-.*",name!=""}) by (name)
              refId: A

          - refId: B
            datasourceUid: __expr__
            model:
              type: reduce
              expression: A
              reducer: last
              settings:
                mode: dropNN
              refId: B

          - refId: D
            datasourceUid: __expr__
            model:
              type: threshold
              expression: B
              conditions:
                - evaluator:
                    type: gt
                    params: [500000000]
                  operator:
                    type: and
                  reducer:
                    type: last
                  type: query
              refId: D

        annotations:
          summary: "High memory on {{ $labels.name }}"
        labels:
          severity: warning
